// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBxSgJ4iO7tZTQebsPTFI5z-shyyBQtrk',
    appId: '1:299472701171:web:18e11cfd7058108346d986',
    messagingSenderId: '299472701171',
    projectId: 'labmaid-8cb7d',
    authDomain: 'labmaid-8cb7d.firebaseapp.com',
    storageBucket: 'labmaid-8cb7d.appspot.com',
    measurementId: 'G-XWF7SGM27P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc8H0RtcbwllVxbgqvxVEubBPtne3utJA',
    appId: '1:299472701171:android:28f6213fa28263be46d986',
    messagingSenderId: '299472701171',
    projectId: 'labmaid-8cb7d',
    storageBucket: 'labmaid-8cb7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBttYXHN5AjqNyqePssCv87kMcCutxmIN8',
    appId: '1:299472701171:ios:7665bb61055f27ff46d986',
    messagingSenderId: '299472701171',
    projectId: 'labmaid-8cb7d',
    storageBucket: 'labmaid-8cb7d.appspot.com',
    iosBundleId: 'com.example.recsseemlabmaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBttYXHN5AjqNyqePssCv87kMcCutxmIN8',
    appId: '1:299472701171:ios:9a3791ddc587df8a46d986',
    messagingSenderId: '299472701171',
    projectId: 'labmaid-8cb7d',
    storageBucket: 'labmaid-8cb7d.appspot.com',
    iosBundleId: 'com.example.recsseemlabmaid.RunnerTests',
  );
}
